config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show,:index]
  root 'recruits#index'
  get 'users/find'=>'users#find'
  get 'recruits/top' => 'recruits#top'
  get 'recruits/list' => 'recruits#list'
  get 'recruits/index' => 'recruits#index'
  get 'recruits/new' => 'recruits#new'
  post 'recruits' => 'recruits#create'
  get 'recruits/:id' => 'recruits#show',as: 'recruit'
  delete 'recruits/:id' => 'recruits#destroy'
  get 'rooms/index' => 'rooms#index'

  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]

  resources :recruit do
    resources :comments, only: [:create]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recruit
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/recruit.rb
class Recruit < ApplicationRecord
    has_many :comments, dependent: :destroy
    NGWORD_REGEX = /(.)\1{4,}/.freeze
    belongs_to :user
    mount_uploader :image, ImageUploader
   
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :image, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :messages, dependent: :destroy
          has_many :entries, dependent: :destroy
          belongs_to :tweets

         has_many :recruits, dependent: :destroy
         validates :name, presence: true 
         validates :profile, length: { maximum: 200 }  

          has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
          has_many :followers, through: :reverse_of_relationships, source: :follower
          has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

          has_many :followings, through: :relationships, source: :followed
          def follow(user_id)
            relationships.create(followed_id: user_id)
          end
          def unfollow(user_id)
            relationships.find_by(followed_id: user_id).destroy
          end
          def following?(user)
            followings.include?(user)
          end
          has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile,:belonging,:image])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
  
    def create
      recruit = Recruit.find(params[:recruit_id])
      comment = recruit.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path)
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path)
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
  end
  

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!, :only => [:create]

    def create
      if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
        @message = Message.create(params.require(:message).permit(:user_id, :content, :room_id).merge(:user_id => current_user.id))
        redirect_to "/rooms/#{@message.room_id}"
      else
        redirect_back(fallback_location: root_path)
      end
    end
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController

   before_action :authenticate_user!,except:[:top]

   def top
   end

   def list
      if params[:search] != nil && params[:search] != ''
         @search = params[:search]
         @users = User.where("profile LIKE ? OR name LIKE ? OR belonging LIKE ?", "%#{@search}%", "%#{@search}%", "%#{@search}%")
      else
         @users = User.all
      end
   end

   def index
      if params[:search] == nil
         @recruit= Recruit.all.order(created_at: :desc)
      elsif params[:search] == ''
         @recruit= Recruit.all.order(created_at: :desc)
      else
         @recruit= Recruit.where(genre:params[:search]).order(created_at: :desc)
      end
   end

   def new
      @recruit = Recruit.new
   end

   def create
      recruit = Recruit.new(recruit_params)
      recruit.user_id = current_user.id
      if recruit.save
         redirect_to :action => "index"
      else
         redirect_to :action =>"new"
      end
   end 

   def show
      @recruit = Recruit.find(params[:id])
      @comments = @recruit.comments
      @comment = Comment.new
   end

   def destroy
      recruit = Recruit.find(params[:id])
      recruit.destroy
      redirect_to action: :index
   end


   private 
   def recruit_params
      params.require(:recruit).permit(:title,:genre,:body,:image,:links)
   end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

    def create
        current_user.follow(params[:user_id])
        redirect_to request.referer
    end
    
    def destroy
        current_user.unfollow(params[:user_id])
        redirect_to request.referer  
    end
    def followings
        @user = User.find(params[:id])
        @users = @user.followings
    end
    
    def followers
        user = User.find(params[:id])
        @users = user.followers
    end

end
    

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @currentEntries = current_user.entries
    myRoomIds = []
  
    @currentEntries.each do | entry |
      myRoomIds << entry.room.id
    end
  
    @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?', current_user.id)
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end
  
  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!, :only => [:show]
  def index
    @users=User.all
  end

  def find
    @finds=User.all
  end
  
  def show
    
      @user = User.find(params[:id]) 
      @followers = @user.followers
      @followings = @user.followings
      @currentUserEntry=Entry.where(user_id: current_user.id)
      @userEntry=Entry.where(user_id: @user.id)
      if @user.id == current_user.id
      else
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id then
              @isRoom = true
              @roomId = cu.room_id
            end
          end
        end
        if @isRoom
        else
          @room = Room.new
          @entry = Entry.new
        end
      end      
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recruits/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<h1>募集一覧</h1>
<h3><button type="button" class="btn btn-outline-danger btn-lg"><%= link_to'新規投稿を作成', recruits_new_path %></button></h3>
<h3>投稿を検索</h3>
<%= form_tag({controller:"recruits",action:"index"}, method: :get) do %>
    <%= select_tag "search",options_for_select([["all",""],["雑談","雑談"],["ゲーム募集","ゲーム募集"],["勉強会","勉強会"],["食事","食事"],["空きコマ","空きコマ"]]) %>
    <%= submit_tag '表示する'  %>
<% end %>

<div class=recruit-container>
    <% @recruit.each do |t| %>
        <div class=recruit>
            <ul>
            <li class=title><%= t.title %></li>
                <div class = user_content>
                    <li><a href="/users/<%= t.user.id %>"><%= image_tag t.user.image_url,size:"50×50" if t.user.image? %></a></li>
                    <li class=name><a href="/users/<%= t.user.id %>"><%= t.user.name %></a></li>
                </div>
                <li>ジャンル:<%= t.genre %></li>
                <%# <%= link_to controller:"tweets",action:"index" do %> %>
                    <%# <%= t.tag %> %>
                <%# <% end %> %>
                <li><%= t.body %></li>
                <li>
                    <% if t.links==nil %>
                    <% else %>
                        <%= Rinku.auto_link(t.links, :all, 'target="_blank"').html_safe %>
                    <% end %>
                </li>
                <li><%= image_tag t.image_url, size: "250x200" if t.image? %></li>
                <li>
                    <i class="far fa-comments"></i>
                    <%= link_to "コメント",recruit_path(t.id) %>
                    <% if user_signed_in? && current_user.id == t.user_id %>
                        <%= link_to "募集を取り下げる",recruit_path(t.id), method: :delete%>
                    <% end %> 
                </li>
                <li class="created_at"><%= t.created_at %></li>
        </div>
    <% end %>
</div>

app/views/recruits/list.html.erb
<%= stylesheet_link_tag 'list', :media => "all" %>
<h3>ユーザーを検索</h3>
<div class=search>
    <%= form_tag({controller:"recruits",action:"list"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索する'  %>
</div>
<% end %>
<% @users.each do|t| %>
    <ul class = profile>

        <div class=main_profile>
            <a href="/users/<%= t.id %>"><%= image_tag t.image_url,size:"50×50" if t.image? %></a>
            <a href="/users/<%= t.id %>"><%= t.name %></a>
        </div>
        <div class=profile_content>
            <li>所属：<%= t.belonging %></br></li>
            <li>プロフィール：<%= t.profile %></br></li>
        </div>
    </ul>
<% end %>

app/views/recruits/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>
<h1>投稿を作成する</h1>
<%= form_for(@recruit) do |f| %>
  <div class="field">
    <label>募集タイトル</label></br>
    <%= f.text_field :title, :size => 140 %></br>

    <label>募集ジャンル </label></br>
    <%= f.select :genre,[["選択してください",""],["雑談","雑談"],["ゲーム募集","ゲーム募集"],["勉強会","勉強会"],["食事","食事"],["空きコマ","空きコマ"]],include_blanl:"選択してください" %></br>
    
    <label>募集場所 </label></br>
    <%= f.text_field :place, :size => 140 %></br>

    <label>詳細 </label></br>
    <%= f.text_field :body, :size => 140 %></br>

    <label>外部リンク</label></br>
    <%= f.text_field :links, :size => 140 %></br>

    <%= f.file_field :image %></br>

    <%= f.submit "募集する" %>
  </div>
<% end %>
<%= link_to "一覧に戻る", recruits_index_path %>

app/views/recruits/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>
<h1>投稿詳細</h1>

<ul class="recruit-content">
  <li class="title"><%= @recruit.title %></li>
  <div class="user_content">
    <li><a href="/users/<%= @recruit.user.id %>"><%= image_tag @recruit.user.image_url,size:"40×40" if @recruit.user.image? %></a></li>
    <li class="name"><a href="/users/<%= @recruit.user.id %>"><%= @recruit.user.name %></a></li>
  </div>
    <li>ジャンル<%= @recruit.genre %></li>
  <li><%= @recruit.body %></li>
  <li><%= image_tag @recruit.image_url, size: "400x300" if @recruit.image? %></li>
</ul>

<div class="comment-wrapper">
<div>コメント一覧</div>
<% @comments.each do |c| %>
  <div>
    <%= c.user.name unless c.user.blank? %>
    <%= c.content %>
  </div>
    <br>
<% end %>

<% if user_signed_in? %>
  <%= form_with(model: [@recruit, @comment], local: true) do |f| %>
    <%= f.text_area :content ,class: "text"%>
    <%= button_tag type: "submit" do %>
      <i class="far fa-comments"></i> コメントする
    <% end %>
  <% end %>
<% end %>
</div>

<%= link_to '投稿一覧へ',recruits_index_path %>

app/views/recruits/top.html.erb
<%= stylesheet_link_tag 'top', :media => "all" %>

<h3>あなたをもう、退屈にはしない</h3>
<% if user_signed_in? %>
<% else %>
    <ul>
        <li><button type="button" class="btn btn-outline-danger btn-lg"><%= link_to "ログイン", recruits_index_path %></button></li>
        <li><button type="button" class="btn btn-outline-danger btn-lg"><%= link_to "新規登録", new_user_registration_path %></button></li>
    </ul>
<% end %>
<div class = passage>
    <div class="flex-item">
        <h5>同じ環境の人と出会える</h5>
        <p>あなたと同じ大学、同じ趣味、同じ思いを抱える人に出会えます</p>
        <p>あなたがコンタクトを取りたいと思った人も必ずあなたとコンタクトを取りたいと思うはずです</p>
    </div>
    <div class="flex-item">
        <h5>暇を潰す相手が見つかる</h5>
        <p>空きコマ、休日のふとした時間、放課後のひと時。何もしないにしては長すぎるし、何かをするには短すぎる時間。</p>
        <p>同じ悩みを抱えた人を探そう！必ずいるから</p>
    </div>
    <div class="flex-item">
        <h5>ネットの壁を越えた友人</h5>
        <p>あなたの出会いはオンラインだけでは飽きたりない</p>
        <p>完全プライベートのDMであなたとお友達のオフ会の予定を立てちゃいましょう！</p>
    </div>
</div>
<h1>さあ、始めよう！出会いを求めて！！</h1>
<% if user_signed_in? %>
<% else %>
    <ul>
        <li><button type="button" class="btn btn-outline-danger btn-lg"><%= link_to "ログイン", recruits_index_path %></button></li>
        <li><button type="button" class="btn btn-outline-danger btn-lg"><%= link_to "新規登録", new_user_registration_path %></button></li>
    </ul>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% @followers.each do |t| %>
  <%= t.name %>
<% end %>  

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <thead>
    <tr>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/rooms/index.html.erb
<%= stylesheet_link_tag 'index_rooms', :media => "all" %>
<div class="list">
  <% @anotherEntries.each do |e| %>
      <%= link_to room_path(e.room.id) do %>
        <%= e.user.name %>とのDM</br>
      <% end %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<%= stylesheet_link_tag 'show_rooms', :media => "all" %>

<h1>メッセージ</h1>

<h4>参加者</h4>
<% @entries.each do |e| %>
  <h5><strong><a href="/users/<%= e.user.id %>"><%= e.user.name%>さん</a></strong></h5>
<% end %>

<hr>
<% if @messages.present? %>
  <% @messages.each do |m| %>
    <small><strong><a href="/users/<%= m.user_id %>"><%= m.user.name %>:</a></strong></small>
    <strong><%= m.content %></strong>
    <strong><%= m.created_at %> </strong>
    <hr>
  <% end %>
<% else %>
  <h3 class="text-center">メッセージはまだありません</h3>
<% end %>

<%= form_for @message do |f| %>
  <%= f.text_field :content, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
  <%= f.hidden_field :room_id, :value => @room.id %>
  <br>
  <%= f.submit "送信" %>
<% end %>

<%= link_to "ユーザー一覧に戻る", users_path %>

app/views/users/index.html.erb
<h1>ダイレクトメッセージ</h1>
<% if user_signed_in? %>
<h2>Hello <%= current_user.name %></h2>
  <% @users.each do |u| %>
  <p><a href="/users/<%= u.id %>"><%= u.name %>さん</a></p>
  <hr>
  <% end %>
  <%= link_to "ログアウト", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to "ユーザーを登録する", new_user_registration_path %>
  <br>
  <%= link_to "ログインする", new_user_session_path %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'show_user', :media => "all" %>

<h1><%= @user.name %>さんのマイページ</h1>
<div class=user-information>

  <div class=user_content>
      <%= image_tag @user.image_url, size: "150x150" if @user.image? %>
    <% if user_signed_in? && current_user.id == @user.id %>
      <div>メールアドレス : <%= @user.email %></div>
    <% end %>
    
    <% if @user.id == current_user.id %>
    <% else %>
      <% if @isRoom == true %>
        <p><a href="/rooms/<%= @roomId %>">チャット</a>
      <% else %>
        <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, :value=> @user.id %>
          <% end %>
          <%= f.submit "チャットを始める" %>
        <% end %>
      <% end %>
    <% end %>
    
    <div>所属 : <%= @user.belonging %></div>
    <div>プロフィール : <%= @user.profile %></div>
    <% if current_user.id == @user.id %>
      <%= link_to "編集する", edit_user_registration_path %>
    <% end %>
  </div>

  <h2>ユーザーの投稿</h2>
  <div>
    <% @user.recruits.each do |t| %>
      <%= t.user.name %>
      <%= t.title %></br>
    <% end %>
  </div>
</div>
<br><%= link_to "Tweet一覧に戻る", recruits_index_path %>