config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show,:index]
  root 'recruits#index'
  get 'users/find'=>'users#find'
  get 'recruits/top' => 'recruits#top'
  get 'recruits/list' => 'recruits#list'
  get 'recruits/index' => 'recruits#index'
  get 'recruits/new' => 'recruits#new'
  post 'recruits' => 'recruits#create'
  get 'recruits/:id' => 'recruits#show',as: 'recruit'
  delete 'recruits/:id' => 'recruits#destroy'
  get 'rooms/index' => 'rooms#index'

  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]

  resources :recruit do
    resources :comments, only: [:create]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recruit
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/recruit.rb
class Recruit < ApplicationRecord
    has_many :comments, dependent: :destroy
    NGWORD_REGEX = /(.)\1{4,}/.freeze
    belongs_to :user
    mount_uploader :image, ImageUploader
   
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :image, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :messages, dependent: :destroy
          has_many :entries, dependent: :destroy
          belongs_to :tweets

         has_many :recruits, dependent: :destroy
         validates :name, presence: true 
         validates :profile, length: { maximum: 200 }  

          has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
          has_many :followers, through: :reverse_of_relationships, source: :follower
          has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

          has_many :followings, through: :relationships, source: :followed
          def follow(user_id)
            relationships.create(followed_id: user_id)
          end
          def unfollow(user_id)
            relationships.find_by(followed_id: user_id).destroy
          end
          def following?(user)
            followings.include?(user)
          end
          has_many :comments, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
  
    def create
      recruit = Recruit.find(params[:recruit_id])
      comment = recruit.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path)
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path)
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
  end
  

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!, :only => [:create]

    def create
      if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
        @message = Message.create(params.require(:message).permit(:user_id, :content, :room_id).merge(:user_id => current_user.id))
        redirect_to "/rooms/#{@message.room_id}"
      else
        redirect_back(fallback_location: root_path)
      end
    end
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController

   before_action :authenticate_user!,except:[:top]

   def top
   end

   def list
      if params[:search] != nil && params[:search] != ''
         @search = params[:search]
         @users = User.where("profile LIKE ? OR name LIKE ? OR belonging LIKE ?", "%#{@search}%", "%#{@search}%", "%#{@search}%")
      else
         @users = User.all
      end
   end

   def index
      if params[:search] == nil
         @recruit= Recruit.all.order(created_at: :desc)
      elsif params[:search] == ''
         @recruit= Recruit.all.order(created_at: :desc)
      else
         @recruit= Recruit.where(genre:params[:search]).order(created_at: :desc)
      end
   end

   def new
      @recruit = Recruit.new
   end

   def create
      recruit = Recruit.new(recruit_params)
      recruit.user_id = current_user.id
      if recruit.save
         redirect_to :action => "index"
      else
         redirect_to :action =>"new"
      end
   end 

   def show
      @recruit = Recruit.find(params[:id])
      @comments = @recruit.comments
      @comment = Comment.new
   end

   def destroy
      recruit = Recruit.find(params[:id])
      recruit.destroy
      redirect_to action: :index
   end


   private 
   def recruit_params
      params.require(:recruit).permit(:title,:genre,:body,:image,:links)
   end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @currentEntries = current_user.entries
    myRoomIds = []
  
    @currentEntries.each do | entry |
      myRoomIds << entry.room.id
    end
  
    @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?', current_user.id)
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end
  
  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!, :only => [:show]
  def index
    @users=User.all
  end

  def find
    @finds=User.all
  end
  
  def show
    
      @user = User.find(params[:id]) 
      @followers = @user.followers
      @followings = @user.followings
      @currentUserEntry=Entry.where(user_id: current_user.id)
      @userEntry=Entry.where(user_id: @user.id)
      if @user.id == current_user.id
      else
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id then
              @isRoom = true
              @roomId = cu.room_id
            end
          end
        end
        if @isRoom
        else
          @room = Room.new
          @entry = Entry.new
        end
      end      
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matchsite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <header>
      <h1>Friend Matching</h1>

      <ul class="nav justify-content-center">
        <li class="nav-item">
          <%= link_to "トップ",recruits_top_path %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "掲示板",recruits_index_path %>
          </li>
          <li class="nav-item">
            <%= link_to "友達を探す",recruits_list_path %>
          </li>
          <li class="nav-item">
            <%= link_to "マイページ", user_path(current_user.id) %>
          </li>
          <li class="nav-item">
            <%= link_to "DM",rooms_index_path %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
        <% end %>
      </ul>


    </header>
      <main>
        <%= yield %>
      </main>
    <footer>
      <div class=content>Copyright © All Rights Reserved.</div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>